"""Order

Revision ID: 9db93731fa2c
Revises: ebfcc0d4fe56
Create Date: 2024-10-04 19:41:39.168596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db93731fa2c'
down_revision: Union[str, None] = 'ebfcc0d4fe56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('Order_id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'Order_id')
    # ### end Alembic commands ###
