"""empty message

Revision ID: b2aed05d4c7a
Revises: 
Create Date: 2024-09-25 20:07:12.733476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2aed05d4c7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('Role', sa.String(), server_default='Customer', nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
