"""Order

Revision ID: ebfcc0d4fe56
Revises: 242838c5ff97
Create Date: 2024-10-04 19:26:40.416149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfcc0d4fe56'
down_revision: Union[str, None] = '242838c5ff97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Orders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('Total', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='Placed', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orders')
    # ### end Alembic commands ###
