# Generated by Django 5.0.6 on 2024-11-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
